server:
  port: 35000

spring:
  config:
    activate:
      on-profile:
      - dev

  rabbitmq:
    host: 129.151.226.176
    port: 5672
    username: default_user_xNhLV7NxWV6Z3e3aBex
    password: A6d9q_VCBMacaa1heD4Z0O8Tws6QfhR_
    virtual-host: /

---

spring:
  config:
    activate:
      on-profile:
      - qa

  rabbitmq:
    host: 129.151.226.176
    port: 5672
    username: default_user_xNhLV7NxWV6Z3e3aBex
    password: A6d9q_VCBMacaa1heD4Z0O8Tws6QfhR_
    virtual-host: /

---

spring:
  config:
    activate:
      on-profile:
      - prod

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    ssl:
      enabled: ${RABBIT_ENABLE_SSL}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWD}
    virtual-host: /

