INSERT INTO NHGRP
(GRUPO_ENT, ANOTACION, F_DESVIG, F_HASVIG, D_LARGA, D_CORTA , SIGLAS, CALLE, PORTAL, BLOQUE,
ESCALERA, PISO, PUERTA, CODPOS, OTRAS_IND, POBLACION, IND_TIPOEMPL, IND_EMPLEADO, LONG_CIP, IND_VAL_EMPL,
IND_ID_CONT, ACTIVIDAD, ENT_CTBLE, CCC_PROV, CCC_NUM, CCC_DIG, BITMAP, ANOTA_USU, ANULACION, ANULA_USU,
CIERRE, CIERRE_USU, ANOT_ORIG, IND_NAU_CIP, IND_AJUSTE_LIQ, ENT_CTABLE_SUPL, IDIOMA_CON, CAL_FESTIVO, IND_IMPR_CLAU, IND_IMPR_RETRIB)
VALUES
(1, '2021-10-16', '2021-10-16', '2021-10-16', 'Subject 4', 'a1c5dcf9', 'aa', 'sss', 1, 'a',
's', 'b', 'c', 2, 'c', 'd', 'e', 'd', 3, 'e',
 '1', 'fsdsdff', 4, 5, 6, 7, 'aa', 'sss', '2021-10-16', 'a',
 '2021-10-16', 'b', '2021-10-16', '2', 'c', 7, 'd', 'q', 7, 8);