DROP TABLE IF EXISTS NHGRP;
CREATE TABLE NHGRP (
  ID int AUTO_INCREMENT PRIMARY KEY,
  GRUPO_ENT int,
  ANOTACION date,
  F_DESVIG date,
  F_HASVIG date,
  D_LARGA varchar(50),
  D_CORTA varchar(20),
  SIGLAS varchar(2),
  CALLE varchar(40),
  PORTAL int,
  BLOQUE varchar(3),
  ESCALERA varchar(2),
  PISO varchar(2),
  PUERTA varchar(2),
  CODPOS int,
  OTRAS_IND varchar(40),
  POBLACION varchar(5),
  IND_TIPOEMPL varchar(1),
  IND_EMPLEADO varchar(1),
  LONG_CIP int,
  IND_VAL_EMPL varchar(1),
  IND_ID_CONT varchar(1),
  ACTIVIDAD varchar(40),
  ENT_CTBLE int,
  CCC_PROV int,
  CCC_NUM int,
  CCC_DIG int,
  BITMAP varchar(15),
  ANOTA_USU varchar(8),
  ANULACION date,
  ANULA_USU varchar(8),
  CIERRE date,
  CIERRE_USU varchar(8),
  ANOT_ORIG date,
  IND_NAU_CIP varchar(1),
  IND_AJUSTE_LIQ varchar(1),
  ENT_CTABLE_SUPL int,
  IDIOMA_CON varchar(10),
  CAL_FESTIVO varchar(18),
  IND_IMPR_CLAU int,
  IND_IMPR_RETRIB int
);